# Generated by Django 5.2 on 2025-05-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Nome único do banco de dados registrado', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banco de Dados Registrado',
                'verbose_name_plural': 'Bancos de Dados Registrados',
                'ordering': ['name'],
            },
        ),
    ]
