# Generated by Django 5.2 on 2025-05-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup_registry', '0001_initial'),
    ]

    operations = [
    ]
